---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: second-kotlin-cicd-app
  namespace: flux-system
spec:
  image: registry.digitalocean.com/sa-container-registry-dev/second-kotlin-cicd-app
  interval: 1m0s
  secretRef:
    name: docker-cfg
