---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: second-kotlin-cicd-app
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: second-kotlin-cicd-app
  policy:
    numerical:
      order: asc

