---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 25.0.0
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: kube-prom-stack
  targetNamespace: monitoring
  interval: 1m0s
  values:
    alertmanager:
      enabled: true
    defaultRules:
      create: true
      rules:
        etcd: false
        kubeScheduler: false
    grafana:
      enabled: true
      persistance:
        enabled: true
        type: pvc
        storageClassName: do-block-storage
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        finalizers:
          - kubernetes.io/pvc-protection
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    # https://github.com/helm/charts/blob/master/stable/prometheus-operator/README.md#prometheus
    prometheus:
      enabled: true
      # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec
      additionalServiceMonitors:
        - name: "loki-monitor"
          selector:
            matchLabels:
              app: loki
              release: loki
          namespaceSelector:
            matchNames:
              - monitoring
          endpoints:
            - port: "http-metrics"
        - name: "promtail-monitor"
          selector:
            matchLabels:
              app: promtail
              release: loki
          namespaceSelector:
            matchNames:
              - monitoring
          endpoints:
            - port: "http-metrics"
        - name: "second-kotlin-cicd-app-monitor"
          selector:
            matchLabels:
              app: second-kotlin-cicd-app
          namespaceSelector:
            matchNames:
              - apps
          endpoints:
            - port: http
              path: "/actuator/prometheus"
              interval: 15s
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
              storageClassName: do-block-storage
    prometheusOperator:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: prometheus-stack-credentials
      valuesKey: grafana_admin_password
      targetPath: grafana.adminPassword
      optional: false
