---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  chart:
    spec:
      chart: bitnami/rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 8.24.12
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: rabbitmq
  targetNamespace: apps
  interval: 1m0s
  values:
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 120Mi
