---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fists-kotlin-cicd-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: ssh://git@github.com/alexsrosa/first-kotlin-cicd-app

