---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: fists-kotlin-cicd-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fists-kotlin-cicd-app
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

